[project]
name = "psq"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "async-lru>=2.0.5",
    "asyncpg>=0.30.0",
    "fastapi>=0.116.0",
    "mcp[cli]>=1.10.1",
    "psycopg2>=2.9.10",
]
